name = "mahashakthi-platform"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://zorilulohlswghkfjuio.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvcmlsdWxvaGxzd2doa2ZqdWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0OTIwNjQsImV4cCI6MjA4NDA2ODA2NH0.s3GnrI9Yh41qqZb-qzDIwBiYzd8H3v-BqLT6mbzVh90"
